language: node_js
cache:
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - 'node'
install:
  - npm prune
  - npm install
script:
  - npm run lint
  - npm run test:coverage-travis
  - make dist
after_success:
  - npm run semantic-release
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
